version: "3.1"
services:
#    postgres:
#      image: postgres:11
#      container_name: postgres
#      volumes:
#         - ./sourcefiles/postgres:/var/lib/postgresql/data
#      environment:
#        - POSTGRES_USER=admin
#        - POSTGRES_PASSWORD=postgres
#        - POSTGRES_DB=habbit
#      ports:
#       - 5431:5432
#      networks:
#            testing_net:
#                ipv4_address: 172.28.1.2

    mysql:
      image: mysql:5.7.22
      container_name: mysql
      ports:
        - 3306:3306
      environment:
        MYSQL_DATABASE: habit
        MYSQL_ROOT_PASSWORD: mysql
      volumes:
        - dbdata:/var/lib/mysql/
        - ./sourcefiles/mysql/my.cnf:/etc/mysql/my.cnf
      networks:
            testing_net:
                ipv4_address: 172.28.1.2

    webserver:
        image: nginx:1.17.6
        container_name: nginx
        volumes:
            - ./application:/var/www
            - ./sourcefiles/nginx:/etc/nginx/conf.d
        ports:
         - 8001:80
        networks:
              testing_net:
                  ipv4_address: 172.28.1.3

    habit:
      build: sourcefiles/php-fpm
      container_name: habit
      working_dir: /var/www
      volumes:
        - ./application:/var/www
        - ./sourcefiles/php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini
      networks:
          testing_net:
              ipv4_address: 172.28.1.4

networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16

volumes:
  dbdata:
    driver: local